spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/scriptql'
    password: '123'
    username: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop