spring:
  datasource:
    url: 'jdbc:postgresql://100.118.68.72:5432/scriptql'
    password: 'postgres'
    username: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
scriptql:
  apprise: 'http://localhost:8000/notify/apprise'
  front: 'http://localhost:1234/'
